pipeline {
    agent any
       
    // environment {    
    //     AWS_SESSION_TOKEN = credentials('session-token')
    // }
    parameters {
        string(name: 'BUCKET_NAME', defaultValue: 'sensei0992002', description: 'S3 bucket name to upload files')

    }
    stages {

        stage('upload to s3') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']])
                    {
                     sh "aws s3 cp ./ s3://${params.BUCKET_NAME}/ --recursive"
                    }
            } 
        }
    }
    post {
        success {
            echo 'Data is insert successfully in S3 ${params.BUCKET_NAME}!'
        }
        failure {
            echo 'Error in insertion in ${params.BUCKET_NAME} Bucket.'
        }
    }
}

